version: "2"

services:
  elasticsearch:
    image: docker.io/elasticsearch:5.6.5
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - $PWD/data/elk/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: docker.io/kibana:5.6.5
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elk

  logstash:
    image: docker.io/logstash:5.6.5
    container_name: logstash
    hostname: logstash
    depends_on:
      - elasticsearch
    volumes:
      - $PWD/data/elk/logstash/conf.d:/etc/logstash/conf.d
      - $PWD/data/elk/logstash/logs:/tmp
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - 7001-7005:7001-7005
      - 4560:4560
    networks:
      - elk

networks:
  elk:
    external: true




























